export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAIL = 'FETCH_CONTACTS_FAIL';

export const FETCH_STATES_START = 'FETCH_STATES_START';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_STATES_FAIL = 'FETCH_STATES_FAIL';

export const FETCH_DISTRICTS_START = 'FETCH_DISTRICTS_START';
export const FETCH_DISTRICTS_SUCCESS = 'FETCH_DISTRICTS_SUCCESS';
export const FETCH_DISTRICTS_FAIL = 'FETCH_DISTRICTS_FAIL';

export const FETCH_STATE_TIMELINE_START = 'FETCH_STATE_TIMELINE_START';
export const FETCH_STATE_TIMELINE_SUCCESS = 'FETCH_STATE_TIMELINE_SUCCESS';
export const FETCH_STATE_TIMELINE_FAIL = 'FETCH_STATE_TIMELINE_FAIL';

export const FETCH_DISTRICT_ZONES_START = 'FETCH_DISTRICT_ZONES_START';
export const FETCH_DISTRICT_ZONES_SUCCESS = 'FETCH_DISTRICT_ZONES_SUCCESS';
export const FETCH_DISTRICT_ZONES_FAIL = 'FETCH_DISTRICT_ZONES_FAIL';